import type {
  Service,
  ServiceRequest,
  User,
  Payment,
  Staff,
  Society,
  Notification,
  Testimonial,
  MonthlyRevenue,
  ServiceStat,
} from "./types"

export const currentUser: User = {
  id: "u1",
  name: "Rajesh Sharma",
  email: "rajesh.sharma@email.com",
  phone: "+91 98765 43210",
  role: "resident",
  society: "Sunrise Heights",
  flatNumber: "A-402",
  joinedDate: "2024-03-15",
}

export const services: Service[] = [
  
  {
    id: "s1",
    name: "Security Services",
    description: "24/7 professional security guards and CCTV monitoring for your society.",
    category: "Security",
    icon: "Shield",
    basePrice: 15000,
    priceUnit: "/month",
    active: true,
    image: "/images/security.jpg",
  },
  {
    id: "s2",
    name: "Plumbing",
    description: "Expert plumbing solutions for repairs, installations, and maintenance.",
    category: "Maintenance",
    icon: "Wrench",
    basePrice: 500,
    priceUnit: "/visit",
    active: true,
    image: "/images/Plumbing.png",
  },
  {
    id: "s3",
    name: "Gardening & Landscaping",
    description: "Professional garden maintenance, landscaping, and plant care services.",
    category: "Outdoor",
    icon: "Trees",
    basePrice: 3000,
    priceUnit: "/month",
    active: true,
    image: "/images/gardening.jpg",
  },
  {
    id: "s4",
    name: "Housekeeping",
    description: "Daily, weekly, or monthly housekeeping services for common areas and flats.",
    category: "Cleaning",
    icon: "Sparkles",
    basePrice: 2000,
    priceUnit: "/month",
    active: true,
    image: "/images/house_keeping-1.jpg",
  },
  {
    id: "s5",
    name: "Deep Cleaning",
    description: "Thorough sanitization and deep cleaning for flats and common areas.",
    category: "Cleaning",
    icon: "SprayCanIcon",
    basePrice: 3500,
    priceUnit: "/session",
    active: true,
    image: "/images/deep.jpg",
  },
  {
    id: "s6",
    name: "Electrical Repairs",
    description: "Licensed electricians for all electrical repairs, wiring, and installations.",
    category: "Maintenance",
    icon: "Zap",
    basePrice: 600,
    priceUnit: "/visit",
    active: true,
    image: "/images/elect.jpg",
  },
  {
    id: "s7",
    name: "Pest Control",
    description: "Safe and effective pest control treatments for homes and common areas.",
    category: "Health",
    icon: "Bug",
    basePrice: 1500,
    priceUnit: "/session",
    active: true,
    image: "/images/pest.jpg",
  },
  {
    id: "s8",
    name: "HVAC Maintenance",
    description: "Air conditioning servicing, repair, and installation by certified technicians.",
    category: "Maintenance",
    icon: "Wind",
    basePrice: 800,
    priceUnit: "/visit",
    active: true,
    image: "/images/havc.jpg",
  },
   {
    id: "s9",
    name: "Administrative Services",
    description: "24/7 professional security guards and CCTV monitoring for your society.",
    category: "Security",
    icon: "Shield",
    basePrice: 15000,
    priceUnit: "/month",
    active: true,
    image: "/images/admin.jpg",
  },
]

export const serviceRequests: ServiceRequest[] = [
  {
    id: "sr1",
    serviceId: "s2",
    serviceName: "Plumbing",
    residentName: "Rajesh Sharma",
    residentFlat: "A-402",
    society: "Sunrise Heights",
    description: "Leaking kitchen faucet, needs replacement.",
    status: "in-progress",
    priority: "high",
    assignedStaff: "Vikram Patel",
    createdAt: "2026-02-18",
    updatedAt: "2026-02-20",
    scheduledDate: "2026-02-21",
  },
  {
    id: "sr2",
    serviceId: "s6",
    serviceName: "Electrical Repairs",
    residentName: "Priya Menon",
    residentFlat: "B-301",
    society: "Sunrise Heights",
    description: "Ceiling fan not working in master bedroom.",
    status: "assigned",
    priority: "medium",
    assignedStaff: "Arjun Singh",
    createdAt: "2026-02-19",
    updatedAt: "2026-02-19",
    scheduledDate: "2026-02-22",
  },
  {
    id: "sr3",
    serviceId: "s7",
    serviceName: "Pest Control",
    residentName: "Amit Patel",
    residentFlat: "C-102",
    society: "Green Valley Residency",
    description: "Cockroach infestation in kitchen area.",
    status: "pending",
    priority: "urgent",
    createdAt: "2026-02-20",
    updatedAt: "2026-02-20",
  },
  {
    id: "sr4",
    serviceId: "s4",
    serviceName: "Housekeeping",
    residentName: "Sneha Kapoor",
    residentFlat: "A-201",
    society: "Sunrise Heights",
    description: "Monthly deep housekeeping for the flat.",
    status: "completed",
    priority: "low",
    assignedStaff: "Meena Devi",
    createdAt: "2026-02-10",
    updatedAt: "2026-02-15",
    completedDate: "2026-02-15",
  },
  {
    id: "sr5",
    serviceId: "s1",
    serviceName: "Security Services",
    residentName: "Rahul Gupta",
    residentFlat: "D-501",
    society: "Palm Grove Estates",
    description: "Additional security guard required for night shift.",
    status: "approved",
    priority: "high",
    createdAt: "2026-02-17",
    updatedAt: "2026-02-18",
  },
  {
    id: "sr6",
    serviceId: "s3",
    serviceName: "Gardening & Landscaping",
    residentName: "Kavita Reddy",
    residentFlat: "B-402",
    society: "Green Valley Residency",
    description: "Common area garden needs trimming and new plants.",
    status: "in-progress",
    priority: "low",
    assignedStaff: "Ramu Kaka",
    createdAt: "2026-02-12",
    updatedAt: "2026-02-16",
    scheduledDate: "2026-02-23",
  },
  {
    id: "sr7",
    serviceId: "s5",
    serviceName: "Deep Cleaning",
    residentName: "Rajesh Sharma",
    residentFlat: "A-402",
    society: "Sunrise Heights",
    description: "Full flat deep cleaning before Holi festival.",
    status: "completed",
    priority: "medium",
    assignedStaff: "Sunita Bai",
    createdAt: "2026-02-05",
    updatedAt: "2026-02-08",
    completedDate: "2026-02-08",
  },
  {
    id: "sr8",
    serviceId: "s8",
    serviceName: "HVAC Maintenance",
    residentName: "Deepak Joshi",
    residentFlat: "C-301",
    society: "Sunrise Heights",
    description: "AC not cooling properly, needs servicing.",
    status: "pending",
    priority: "medium",
    createdAt: "2026-02-21",
    updatedAt: "2026-02-21",
  },
  {
    id: "sr9",
    serviceId: "s2",
    serviceName: "Plumbing",
    residentName: "Anita Desai",
    residentFlat: "A-103",
    society: "Palm Grove Estates",
    description: "Bathroom water heater pipe leaking.",
    status: "assigned",
    priority: "high",
    assignedStaff: "Vikram Patel",
    createdAt: "2026-02-20",
    updatedAt: "2026-02-21",
    scheduledDate: "2026-02-24",
  },
  {
    id: "sr10",
    serviceId: "s6",
    serviceName: "Electrical Repairs",
    residentName: "Sanjay Kumar",
    residentFlat: "B-502",
    society: "Green Valley Residency",
    description: "Power outage in one room, circuit breaker issue.",
    status: "completed",
    priority: "urgent",
    assignedStaff: "Arjun Singh",
    createdAt: "2026-02-14",
    updatedAt: "2026-02-14",
    completedDate: "2026-02-14",
  },
  {
    id: "sr11",
    serviceId: "s7",
    serviceName: "Pest Control",
    residentName: "Meera Nair",
    residentFlat: "D-201",
    society: "Palm Grove Estates",
    description: "Termite treatment for wooden furniture.",
    status: "in-progress",
    priority: "high",
    assignedStaff: "Ravi Kumar",
    createdAt: "2026-02-16",
    updatedAt: "2026-02-19",
    scheduledDate: "2026-02-22",
  },
  {
    id: "sr12",
    serviceId: "s4",
    serviceName: "Housekeeping",
    residentName: "Vikash Agarwal",
    residentFlat: "C-401",
    society: "Sunrise Heights",
    description: "Weekly housekeeping subscription renewal.",
    status: "approved",
    priority: "low",
    createdAt: "2026-02-19",
    updatedAt: "2026-02-20",
  },
  {
    id: "sr13",
    serviceId: "s3",
    serviceName: "Gardening & Landscaping",
    residentName: "Pooja Mishra",
    residentFlat: "A-501",
    society: "Sunrise Heights",
    description: "Balcony garden setup with potted plants.",
    status: "pending",
    priority: "low",
    createdAt: "2026-02-22",
    updatedAt: "2026-02-22",
  },
  {
    id: "sr14",
    serviceId: "s5",
    serviceName: "Deep Cleaning",
    residentName: "Rohit Verma",
    residentFlat: "B-203",
    society: "Green Valley Residency",
    description: "Post-renovation deep cleaning of entire flat.",
    status: "cancelled",
    priority: "medium",
    createdAt: "2026-02-11",
    updatedAt: "2026-02-13",
  },
  {
    id: "sr15",
    serviceId: "s8",
    serviceName: "HVAC Maintenance",
    residentName: "Nisha Pillai",
    residentFlat: "D-302",
    society: "Palm Grove Estates",
    description: "Annual AC maintenance and gas refill.",
    status: "completed",
    priority: "low",
    assignedStaff: "Suresh Yadav",
    createdAt: "2026-02-01",
    updatedAt: "2026-02-03",
    completedDate: "2026-02-03",
  },
]

export const payments: Payment[] = [
  {
    id: "p1",
    requestId: "sr4",
    serviceName: "Housekeeping",
    amount: 2000,
    status: "paid",
    date: "2026-02-15",
    invoiceNumber: "INV-2026-0041",
    residentName: "Sneha Kapoor",
    society: "Sunrise Heights",
  },
  {
    id: "p2",
    requestId: "sr7",
    serviceName: "Deep Cleaning",
    amount: 3500,
    status: "paid",
    date: "2026-02-08",
    invoiceNumber: "INV-2026-0038",
    residentName: "Rajesh Sharma",
    society: "Sunrise Heights",
  },
  {
    id: "p3",
    requestId: "sr10",
    serviceName: "Electrical Repairs",
    amount: 1200,
    status: "paid",
    date: "2026-02-14",
    invoiceNumber: "INV-2026-0040",
    residentName: "Sanjay Kumar",
    society: "Green Valley Residency",
  },
  {
    id: "p4",
    requestId: "sr1",
    serviceName: "Plumbing",
    amount: 850,
    status: "pending",
    date: "2026-02-21",
    invoiceNumber: "INV-2026-0045",
    residentName: "Rajesh Sharma",
    society: "Sunrise Heights",
  },
  {
    id: "p5",
    requestId: "sr15",
    serviceName: "HVAC Maintenance",
    amount: 2400,
    status: "paid",
    date: "2026-02-03",
    invoiceNumber: "INV-2026-0035",
    residentName: "Nisha Pillai",
    society: "Palm Grove Estates",
  },
  {
    id: "p6",
    requestId: "sr5",
    serviceName: "Security Services",
    amount: 15000,
    status: "overdue",
    date: "2026-02-01",
    invoiceNumber: "INV-2026-0033",
    residentName: "Rahul Gupta",
    society: "Palm Grove Estates",
  },
  {
    id: "p7",
    requestId: "sr6",
    serviceName: "Gardening & Landscaping",
    amount: 4500,
    status: "pending",
    date: "2026-02-23",
    invoiceNumber: "INV-2026-0047",
    residentName: "Kavita Reddy",
    society: "Green Valley Residency",
  },
  {
    id: "p8",
    requestId: "sr11",
    serviceName: "Pest Control",
    amount: 2500,
    status: "pending",
    date: "2026-02-22",
    invoiceNumber: "INV-2026-0046",
    residentName: "Meera Nair",
    society: "Palm Grove Estates",
  },
]

export const staff: Staff[] = [
  {
    id: "st1",
    name: "Vikram Patel",
    email: "vikram.patel@abgroup.com",
    phone: "+91 99887 65432",
    specialty: "Plumbing",
    availability: true,
    assignedRequests: 3,
    rating: 4.8,
    joinedDate: "2023-06-15",
  },
  {
    id: "st2",
    name: "Arjun Singh",
    email: "arjun.singh@abgroup.com",
    phone: "+91 98765 12345",
    specialty: "Electrical",
    availability: true,
    assignedRequests: 2,
    rating: 4.9,
    joinedDate: "2023-08-20",
  },
  {
    id: "st3",
    name: "Meena Devi",
    email: "meena.devi@abgroup.com",
    phone: "+91 97654 32100",
    specialty: "Housekeeping",
    availability: true,
    assignedRequests: 4,
    rating: 4.7,
    joinedDate: "2024-01-10",
  },
  {
    id: "st4",
    name: "Ramu Kaka",
    email: "ramu.k@abgroup.com",
    phone: "+91 96543 21098",
    specialty: "Gardening",
    availability: true,
    assignedRequests: 2,
    rating: 4.6,
    joinedDate: "2023-04-05",
  },
  {
    id: "st5",
    name: "Sunita Bai",
    email: "sunita.bai@abgroup.com",
    phone: "+91 95432 10987",
    specialty: "Deep Cleaning",
    availability: false,
    assignedRequests: 1,
    rating: 4.8,
    joinedDate: "2024-03-12",
  },
  {
    id: "st6",
    name: "Ravi Kumar",
    email: "ravi.kumar@abgroup.com",
    phone: "+91 94321 09876",
    specialty: "Pest Control",
    availability: true,
    assignedRequests: 3,
    rating: 4.5,
    joinedDate: "2023-09-01",
  },
  {
    id: "st7",
    name: "Suresh Yadav",
    email: "suresh.yadav@abgroup.com",
    phone: "+91 93210 98765",
    specialty: "HVAC",
    availability: true,
    assignedRequests: 1,
    rating: 4.7,
    joinedDate: "2024-05-20",
  },
  {
    id: "st8",
    name: "Dinesh Gupta",
    email: "dinesh.gupta@abgroup.com",
    phone: "+91 92109 87654",
    specialty: "Security",
    availability: true,
    assignedRequests: 0,
    rating: 4.4,
    joinedDate: "2024-07-15",
  },
]

export const societies: Society[] = [
  {
    id: "soc1",
    name: "Sunrise Heights",
    address: "Sector 52, Gurugram, Haryana",
    totalFlats: 200,
    activeResidents: 178,
    managerId: "m1",
    managerName: "Anil Mehta",
  },
  {
    id: "soc2",
    name: "Green Valley Residency",
    address: "Whitefield, Bangalore, Karnataka",
    totalFlats: 150,
    activeResidents: 132,
    managerId: "m2",
    managerName: "Priya Nair",
  },
  {
    id: "soc3",
    name: "Palm Grove Estates",
    address: "Bandra West, Mumbai, Maharashtra",
    totalFlats: 120,
    activeResidents: 108,
    managerId: "m3",
    managerName: "Sunil Deshmukh",
  },
]

export const notifications: Notification[] = [
  {
    id: "n1",
    title: "Service Request Update",
    message: "Your plumbing request has been assigned to Vikram Patel.",
    type: "info",
    read: false,
    createdAt: "2026-02-20T10:30:00",
    targetRole: "resident",
  },
  {
    id: "n2",
    title: "Payment Reminder",
    message: "Payment of Rs. 850 for plumbing service is pending.",
    type: "warning",
    read: false,
    createdAt: "2026-02-21T09:00:00",
    targetRole: "resident",
  },
  {
    id: "n3",
    title: "New Request Pending Approval",
    message: "Amit Patel from C-102 has submitted an urgent pest control request.",
    type: "warning",
    read: false,
    createdAt: "2026-02-20T11:15:00",
    targetRole: "manager",
  },
  {
    id: "n4",
    title: "Staff Availability Update",
    message: "Sunita Bai has been marked as unavailable for the next 3 days.",
    type: "info",
    read: true,
    createdAt: "2026-02-19T14:00:00",
    targetRole: "admin",
  },
  {
    id: "n5",
    title: "Monthly Report Ready",
    message: "February 2026 revenue report is ready for review.",
    type: "success",
    read: false,
    createdAt: "2026-02-22T08:00:00",
    targetRole: "admin",
  },
  {
    id: "n6",
    title: "Service Completed",
    message: "Deep cleaning service for flat A-402 has been completed.",
    type: "success",
    read: true,
    createdAt: "2026-02-08T16:00:00",
    targetRole: "all",
  },
  {
    id: "n7",
    title: "Emergency: Power Outage",
    message: "Scheduled power maintenance in Block B from 10 AM to 2 PM tomorrow.",
    type: "error",
    read: false,
    createdAt: "2026-02-22T18:00:00",
    targetRole: "all",
  },
]

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Rajesh Sharma",
    society: "Sunrise Heights, Gurugram",
    rating: 5,
   
    review:
      "AB Group has transformed our society management. Their security team is incredibly professional, and maintenance requests are handled within hours. Highly recommend their services!",
   image: "/images/prof1.jpg",
    },
  {
    id: "t2",
    name: "Priya Menon",
    society: "Green Valley Residency, Bangalore",
    rating: 5,
    image: "/images/prof2.jpg",
    review:
      "The housekeeping service is exceptional. Our common areas have never been cleaner. The online portal makes it super easy to track everything.",
  },
  {
    id: "t3",
    name: "Amit Patel",
    society: "Palm Grove Estates, Mumbai",
    rating: 4,
    image: "/images/prof3.jpg",
    review:
      "Reliable and transparent services. The gardening team does a fantastic job maintaining our society grounds. The pricing is very competitive too.",
  },
  {
    id: "t4",
    name: "Kavita Reddy",
    society: "Green Valley Residency, Bangalore",
    rating: 5,
    image: "/images/prof4.jpg",
    review:
      "Switched to AB Group 6 months ago and the difference is night and day. Professional staff, quick response times, and the digital billing system is a game-changer.",
  },
  {
    id: "t5",
    name: "Deepak Joshi",
    society: "Sunrise Heights, Gurugram",
    rating: 4,
    image: "/images/prof5.jpg",
    review:
      "The pest control and HVAC services are top-notch. They use safe, eco-friendly products and their technicians are always on time. Great experience overall.",
  },
]

export const monthlyRevenue: MonthlyRevenue[] = [
  { month: "Sep", revenue: 285000, requests: 42 },
  { month: "Oct", revenue: 320000, requests: 48 },
  { month: "Nov", revenue: 310000, requests: 45 },
  { month: "Dec", revenue: 365000, requests: 55 },
  { month: "Jan", revenue: 342000, requests: 51 },
  { month: "Feb", revenue: 389000, requests: 58 },
]

export const serviceStats: ServiceStat[] = [
  { name: "Security", requests: 45, revenue: 675000 },
  { name: "Plumbing", requests: 68, revenue: 54400 },
  { name: "Gardening", requests: 32, revenue: 96000 },
  { name: "Housekeeping", requests: 85, revenue: 170000 },
  { name: "Deep Clean", requests: 41, revenue: 143500 },
  { name: "Electrical", requests: 58, revenue: 46400 },
  { name: "Pest Control", requests: 38, revenue: 57000 },
  { name: "HVAC", requests: 29, revenue: 34800 },
]

export const residents: User[] = [
  { id: "r1", name: "Rajesh Sharma", email: "rajesh@email.com", phone: "+91 98765 43210", role: "resident", society: "Sunrise Heights", flatNumber: "A-402", joinedDate: "2024-03-15" },
  { id: "r2", name: "Priya Menon", email: "priya@email.com", phone: "+91 98765 43211", role: "resident", society: "Sunrise Heights", flatNumber: "B-301", joinedDate: "2024-04-20" },
  { id: "r3", name: "Sneha Kapoor", email: "sneha@email.com", phone: "+91 98765 43212", role: "resident", society: "Sunrise Heights", flatNumber: "A-201", joinedDate: "2024-01-10" },
  { id: "r4", name: "Deepak Joshi", email: "deepak@email.com", phone: "+91 98765 43213", role: "resident", society: "Sunrise Heights", flatNumber: "C-301", joinedDate: "2024-06-05" },
  { id: "r5", name: "Pooja Mishra", email: "pooja@email.com", phone: "+91 98765 43214", role: "resident", society: "Sunrise Heights", flatNumber: "A-501", joinedDate: "2024-07-22" },
  { id: "r6", name: "Vikash Agarwal", email: "vikash@email.com", phone: "+91 98765 43215", role: "resident", society: "Sunrise Heights", flatNumber: "C-401", joinedDate: "2024-02-18" },
  { id: "r7", name: "Sanjay Kumar", email: "sanjay@email.com", phone: "+91 98765 43216", role: "resident", society: "Green Valley Residency", flatNumber: "B-502", joinedDate: "2024-05-30" },
  { id: "r8", name: "Amit Patel", email: "amit@email.com", phone: "+91 98765 43217", role: "resident", society: "Green Valley Residency", flatNumber: "C-102", joinedDate: "2024-08-12" },
  { id: "r9", name: "Kavita Reddy", email: "kavita@email.com", phone: "+91 98765 43218", role: "resident", society: "Green Valley Residency", flatNumber: "B-402", joinedDate: "2024-03-28" },
  { id: "r10", name: "Rohit Verma", email: "rohit@email.com", phone: "+91 98765 43219", role: "resident", society: "Green Valley Residency", flatNumber: "B-203", joinedDate: "2024-09-01" },
]
